In [2]:
import numpy as np

In [3]:
data=np.random.randn(2,3)

In [4]:
data

array([[-0.19064303,  1.06543772,  0.28737604],
       [ 0.88317689, -0.19155577, -1.42406193]])

In [5]:
data2=[[1,2,3,4],[5,6,7,8]]

In [6]:
arr2=np.array(data2)

In [7]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr1=np.array([1,2,3],dtype=np.float)

In [9]:
arr1.dtype

dtype('float64')

In [10]:
arr=np.array([[1,2,3],[4,5,6]])

In [11]:
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [13]:
arr-arr


array([[0, 0, 0],
       [0, 0, 0]])

In [14]:
arr+arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [15]:
arr2=arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [18]:
arr2=np.array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [19]:
arr2>arr1

array([[False, False, False],
       [ True,  True, False]])

In [22]:
arr_slice=arr2[5:8]

In [23]:
arr_slice

array([], shape=(0, 3), dtype=float64)

#Basic Indexing and Slicing

In [26]:
arr=np.arange(10)

In [27]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr[5]

5

In [29]:
arr[5:8]

array([5, 6, 7])

In [31]:
arr[5:8]=12

In [32]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [33]:
arr_slice=arr[5:8]

In [34]:
arr_slice


array([12, 12, 12])

In [35]:
arr_slice[1]=12345

In [36]:
#Mutation is reflected in parent cells
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [37]:
arr_slice[:]=64

In [38]:
arr_slice

array([64, 64, 64])

In [39]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

#Because of performace issue numpy is relying more on copying the data rather than changing it. Since numpy works with large number of data.

#Boolaean Indexing

In [3]:
names=np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [4]:
data=np.random.randn(7,4)

In [5]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [6]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [7]:
data

array([[-0.65212944,  0.47962319,  1.26911894, -0.69730522],
       [ 0.73341154, -0.25393661, -1.43719984,  1.00804648],
       [-0.05078662,  0.73192395, -2.75003393, -1.27911636],
       [-0.37358934,  0.52398526, -0.69818845, -1.11912273],
       [ 1.0866298 , -0.10669192,  1.27218494,  0.84492574],
       [-0.05565115,  0.65707535,  0.42204977, -0.63696136],
       [-0.63644934, -1.01424602,  0.03959177,  1.64910741]])

In [8]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [12]:
data[names=='Bob']

array([[-0.65212944,  0.47962319,  1.26911894, -0.69730522],
       [-0.37358934,  0.52398526, -0.69818845, -1.11912273]])

In [13]:
data[data<0]=0

In [14]:
data

array([[0.        , 0.47962319, 1.26911894, 0.        ],
       [0.73341154, 0.        , 0.        , 1.00804648],
       [0.        , 0.73192395, 0.        , 0.        ],
       [0.        , 0.52398526, 0.        , 0.        ],
       [1.0866298 , 0.        , 1.27218494, 0.84492574],
       [0.        , 0.65707535, 0.42204977, 0.        ],
       [0.        , 0.        , 0.03959177, 1.64910741]])

#Fancy Indexing

In [15]:
arr=np.empty((8,4))

In [16]:
for i in range(8):
    arr[i]=i

In [17]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

# Transposing Arrays and Swapping Axes

In [19]:
arr=np.arange(15).reshape((3,5))

In [20]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [22]:
arr=np.random.randn(6,3)

In [23]:
arr

array([[-0.73635112, -0.42250278, -0.92082968],
       [-0.02787614, -0.77568727, -1.57776064],
       [-1.55481086, -1.13312077, -0.59061191],
       [ 0.70618042, -1.30058309, -1.73857181],
       [-0.29631233,  1.08830388,  0.07735524],
       [ 0.35936795, -0.48341626, -0.09701309]])

In [24]:
np.dot(arr.T,arr)

array([[3.67606394, 0.67987355, 0.35479557],
       [0.67987355, 5.17377502, 4.67437738],
       [0.35479557, 4.67437738, 6.72410566]])

In [26]:
arr

array([[-0.73635112, -0.42250278, -0.92082968],
       [-0.02787614, -0.77568727, -1.57776064],
       [-1.55481086, -1.13312077, -0.59061191],
       [ 0.70618042, -1.30058309, -1.73857181],
       [-0.29631233,  1.08830388,  0.07735524],
       [ 0.35936795, -0.48341626, -0.09701309]])

#UniversalFunctions: Fast elsement wise array functions

In [35]:
arr=[0,1,2,3,4,5,6,7,8,9]

In [37]:
arr

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [40]:
#Array Oriented Programming with Arrays